// Products list API — reads from generated data file.

import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

interface Product {
  id: number
  name: string
  code: string
  category: string
  image: string
  thumbnail: string
  badge: string | null
  rating: number
  reviews: number
}

// Read once at startup (file is static, generated by scripts/generate-api-data.js)
const dataPath = resolve(process.cwd(), 'server/data/products.json')
let allProducts: Product[] = []
try {
  allProducts = JSON.parse(readFileSync(dataPath, 'utf-8'))
}
catch {
  // eslint-disable-next-line no-console
  console.warn('[api/products] Could not load server/data/products.json')
}

export default defineEventHandler((event) => {
  setResponseHeaders(event, {
    'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300',
    'Content-Type': 'application/json',
  })

  // Return only the fields the list page needs
  return allProducts.map(p => ({
    id: p.id,
    name: p.name,
    code: p.code,
    category: p.category,
    image: p.image,
    thumbnail: p.thumbnail,
    badge: p.badge,
    rating: p.rating,
    reviews: p.reviews,
  }))
})
