// Product Detail API — returns extended product data for PDP
// Follows same cache/typing pattern as /api/products.ts

interface ProductDetail {
  id: number
  name: string
  category: string
  image: string
  images: string[]
  rating: number
  reviews: number
  badge: string | null
  price: number
  originalPrice: number | null
  description: string
  productInfo: string
  advantages: string[]
  usage: string[]
  storage: string[]
  colors: { name: string; hex: string }[]
  specs: { label: string; value: string }[]
  inTheBox: string[]
  features: string[]
}

const productDetails: Record<number, ProductDetail> = {
  1: {
    id: 1,
    name: 'Bộ hộp đựng thực phẩm Lock&Lock 5 món',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80',
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80',
    ],
    rating: 5,
    reviews: 128,
    badge: 'Mới',
    price: 349000,
    originalPrice: null,
    description: 'Bộ hộp đựng thực phẩm Lock&Lock 5 món với nắp đậy kín khí, giữ thức ăn tươi ngon lâu hơn. Chất liệu nhựa PP cao cấp, an toàn cho sức khỏe, có thể sử dụng trong lò vi sóng.',
    productInfo: 'Bộ hộp đựng thực phẩm Lock&Lock 5 món là sản phẩm bảo quản thực phẩm cao cấp được làm từ chất liệu nhựa PP nguyên sinh an toàn thực phẩm, thiết kế nắp đậy 4 cạnh khóa kín khí giúp giữ thức ăn tươi ngon lâu hơn. Với 5 kích cỡ đa dạng từ 350ml đến 2L, bộ sản phẩm đáp ứng mọi nhu cầu bảo quản từ gia vị, thức ăn thừa đến trái cây, rau củ. Thiết kế trong suốt giúp dễ dàng nhận biết thực phẩm bên trong, tiết kiệm thời gian tìm kiếm.',
    advantages: [
      'Chất liệu nhựa PP nguyên sinh an toàn thực phẩm, không chứa BPA.',
      'Nắp đậy 4 cạnh khóa kín khí 100%, giữ thức ăn tươi ngon lâu hơn.',
      'Chịu nhiệt từ -20°C đến 120°C, dùng được trong lò vi sóng (tháo nắp).',
      'Thiết kế trong suốt, dễ nhận biết thực phẩm bên trong.',
      'Có thể xếp chồng gọn gàng, tiết kiệm không gian tủ lạnh.',
      'Dễ vệ sinh, có thể rửa bằng máy rửa chén.',
    ],
    usage: [
      'Dùng để bảo quản thực phẩm trong tủ lạnh hoặc tủ đông.',
      'Có thể hâm nóng thức ăn trong lò vi sóng (nhớ tháo nắp).',
      'Phù hợp mang theo cơm trưa, picnic.',
    ],
    storage: [
      'Tránh tiếp xúc với nguồn nhiệt cao hoặc ánh sáng mặt trời trực tiếp trong thời gian dài.',
      'Không sử dụng trong lò nướng.',
      'Rửa sạch và lau khô sau mỗi lần sử dụng.',
    ],
    colors: [
      { name: 'Trong suốt', hex: '#E8E8E8' },
      { name: 'Xanh mint', hex: '#0D6E6E' },
      { name: 'Hồng pastel', hex: '#F5A5B8' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Nhựa PP an toàn thực phẩm' },
      { label: 'Bộ gồm', value: '5 hộp: 350ml, 500ml, 800ml, 1.2L, 2L' },
      { label: 'Chịu nhiệt', value: '-20°C đến 120°C' },
      { label: 'Lò vi sóng', value: 'Có (tháo nắp)' },
      { label: 'Máy rửa chén', value: 'Có' },
      { label: 'Xuất xứ', value: 'Hàn Quốc' },
    ],
    inTheBox: ['5 hộp đựng các kích cỡ', '5 nắp đậy kín khí', 'Hướng dẫn sử dụng', 'Túi đựng bảo quản'],
    features: ['Kín khí 100%', 'An toàn thực phẩm', 'Dùng được lò vi sóng'],
  },
  2: {
    id: 2,
    name: 'Kệ gia vị nhà bếp 3 tầng bằng inox',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
      'https://images.unsplash.com/photo-1584568694244-14fbdf83bd30?w=800&q=80',
    ],
    rating: 4,
    reviews: 85,
    badge: null,
    price: 189000,
    originalPrice: null,
    description: 'Kệ gia vị 3 tầng bằng inox 304 cao cấp, thiết kế đơn giản gọn gàng. Dễ dàng tháo lắp và vệ sinh, phù hợp mọi không gian bếp.',
    productInfo: 'Kệ gia vị nhà bếp 3 tầng được làm từ inox 304 cao cấp chống gỉ, thiết kế nhỏ gọn với 3 tầng giúp sắp xếp gia vị, lọ tương, dầu ăn ngăn nắp. Chân kệ có đệm cao su chống trơn trượt, đảm bảo kệ luôn đứng vững trên mọi bề mặt. Kiểu dáng tối giản, hiện đại phù hợp mọi phong cách nhà bếp.',
    advantages: [
      'Chất liệu inox 304 cao cấp, chống gỉ, bền bỉ theo thời gian.',
      'Thiết kế 3 tầng gọn gàng, tối ưu không gian bếp.',
      'Chân kệ có đệm cao su chống trơn trượt trên mọi bề mặt.',
      'Dễ dàng tháo lắp, vệ sinh, không cần dụng cụ.',
      'Tải trọng 5kg mỗi tầng, đặt được nhiều loại gia vị.',
    ],
    usage: [
      'Đặt trên bàn bếp hoặc kệ tủ để sắp xếp gia vị, lọ tương, dầu ăn.',
      'Có thể dùng trong phòng tắm để đựng mỹ phẩm, dầu gội.',
    ],
    storage: [
      'Tránh tiếp xúc với hóa chất mạnh.',
      'Lau khô sau khi vệ sinh để giữ bóng sáng.',
    ],
    colors: [
      { name: 'Bạc', hex: '#C0C0C0' },
      { name: 'Đen', hex: '#1A1A1A' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Inox 304' },
      { label: 'Kích thước', value: '25 x 15 x 38 cm' },
      { label: 'Tải trọng', value: '5kg mỗi tầng' },
      { label: 'Lắp đặt', value: 'Không cần khoan' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Kệ 3 tầng', 'Bộ phụ kiện lắp đặt', 'Hướng dẫn sử dụng'],
    features: ['Inox 304 chống gỉ', 'Không cần khoan', 'Dễ tháo lắp'],
  },
  3: {
    id: 3,
    name: 'Kệ nhà tắm dán tường không cần khoan',
    category: 'bathroom',
    image: 'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
      'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=800&q=80',
    ],
    rating: 4,
    reviews: 62,
    badge: '-30%',
    price: 129000,
    originalPrice: 185000,
    description: 'Kệ nhà tắm dán tường siêu chắc, không cần khoan đục. Thiết kế thoát nước thông minh, chịu lực tốt, phù hợp đặt dầu gội, sữa tắm, xà phòng.',
    productInfo: 'Kệ nhà tắm dán tường là giải pháp lưu trữ thông minh cho phòng tắm mà không cần phải khoan đục tường. Sử dụng miếng dán 3M siêu chắc, kệ có thể chịu lực lên đến 8kg. Thiết kế khe thoát nước ở đáy kệ giúp nước từ chai dầu gội, sữa tắm nhanh chóng thoát ra, giữ kệ luôn khô ráo, sạch sẽ.',
    advantages: [
      'Chất liệu nhựa ABS kết hợp inox chống gỉ, bền bỉ trong môi trường ẩm ướt.',
      'Dán tường bằng miếng dán 3M, không cần khoan đục, không hư tường.',
      'Thiết kế khe thoát nước thông minh, luôn giữ kệ khô ráo.',
      'Chịu lực lên đến 8kg, đặt được nhiều đồ dùng.',
      'Chống nước IPX5, an toàn sử dụng trong phòng tắm.',
    ],
    usage: [
      'Dùng để đựng dầu gội, sữa tắm, xà phòng và các vật dụng nhà tắm.',
      'Lắp đặt trên tường phòng tắm, nhà bếp hoặc ban công.',
      'Lau sạch bề mặt tường trước khi dán để đảm bảo độ bám dính.',
    ],
    storage: [
      'Tránh đặt vật nặng quá 8kg lên kệ.',
      'Không tháo dỡ sau khi dán 24h đầu để keo đạt độ bám tối đa.',
      'Vệ sinh kệ bằng khăn ẩm, tránh hóa chất mạnh.',
    ],
    colors: [
      { name: 'Trắng', hex: '#FFFFFF' },
      { name: 'Xám', hex: '#6B7280' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Nhựa ABS + Inox' },
      { label: 'Kích thước', value: '30 x 12 x 8 cm' },
      { label: 'Tải trọng', value: '8kg' },
      { label: 'Lắp đặt', value: 'Miếng dán 3M' },
      { label: 'Chống nước', value: 'IPX5' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Kệ nhà tắm', '2 miếng dán 3M', 'Hướng dẫn lắp đặt'],
    features: ['Không cần khoan', 'Chịu lực 8kg', 'Thoát nước nhanh'],
  },
  4: {
    id: 4,
    name: 'Thùng rác phân loại 3 ngăn 45L',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    rating: 5,
    reviews: 204,
    badge: 'Mới',
    price: 459000,
    originalPrice: null,
    description: 'Thùng rác phân loại 3 ngăn thông minh, giúp phân loại rác hữu cơ, tái chế và rác thường. Thiết kế đạp chân tiện lợi, nắp đậy kín ngăn mùi.',
    productInfo: 'Thùng rác phân loại 3 ngăn 45L là giải pháp phân loại rác thông minh cho gia đình hiện đại. Với 3 ngăn riêng biệt (hữu cơ, tái chế, rác thường), mỗi ngăn 15L, sản phẩm giúp gia đình thực hiện phân loại rác tại nguồn dễ dàng. Thiết kế đạp chân mở nắp tiện lợi, không cần dùng tay, nắp đậy kín ngăn mùi hôi hiệu quả. Vỏ ngoài bằng thép không gỉ sang trọng, 3 xô nhựa rời bên trong dễ tháo rửa.',
    advantages: [
      'Phân loại rác 3 ngăn: hữu cơ, tái chế, rác thường.',
      'Cơ chế đạp chân mở nắp tiện lợi, không cần dùng tay.',
      'Nắp đậy kín, ngăn mùi hôi hiệu quả.',
      'Vỏ ngoài thép không gỉ sang trọng, dễ lau chùi.',
      '3 xô nhựa rời bên trong, dễ tháo rửa, thay túi rác.',
      'Nhãn phân loại rác đi kèm, giúp cả gia đình cùng thực hiện.',
    ],
    usage: [
      'Đặt tại khu vực bếp, hành lang hoặc ban công.',
      'Phân loại rác theo 3 ngăn: hữu cơ (thức ăn thừa), tái chế (nhựa, giấy), rác thường.',
      'Đạp chân nhẹ để mở nắp, thả rác vào ngăn phù hợp.',
    ],
    storage: [
      'Vệ sinh xô nhựa bên trong định kỳ mỗi tuần.',
      'Lau vỏ ngoài bằng khăn ẩm, tránh sử dụng chất tẩy mạnh.',
      'Đặt nơi khô ráo, thoáng mát.',
    ],
    colors: [
      { name: 'Đen', hex: '#1A1A1A' },
      { name: 'Xám', hex: '#6B7280' },
      { name: 'Trắng', hex: '#F5F5F5' },
    ],
    specs: [
      { label: 'Dung tích', value: '45L (15L x 3 ngăn)' },
      { label: 'Chất liệu', value: 'Thép không gỉ + PP' },
      { label: 'Kích thước', value: '60 x 30 x 65 cm' },
      { label: 'Cơ chế', value: 'Đạp chân mở nắp' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Thùng rác 3 ngăn', '3 xô nhựa rời', 'Nhãn phân loại', 'Hướng dẫn sử dụng'],
    features: ['Phân loại 3 ngăn', 'Đạp chân tiện lợi', 'Ngăn mùi hiệu quả'],
  },
  5: {
    id: 5,
    name: 'Rổ rá đa năng hình chữ nhật 4L',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    rating: 4,
    reviews: 43,
    badge: null,
    price: 79000,
    originalPrice: null,
    description: 'Rổ rá đa năng hình chữ nhật 4L, thiết kế 2 lớp tiện lợi cho rửa rau, vo gạo, ráo nước.',
    productInfo: 'Rổ rá đa năng hình chữ nhật 4L với thiết kế 2 lớp thông minh: lớp rổ lỗ thoát nước nhanh và lớp rá đựng bên dưới giữ nước khi cần ngâm rửa. Chất liệu nhựa PP nguyên sinh an toàn thực phẩm, không BPA. Hình chữ nhật tiết kiệm không gian hơn rổ tròn truyền thống, dễ dàng xếp gọn trong tủ bếp.',
    advantages: [
      'Thiết kế 2 lớp rổ rá thông minh, vừa rửa vừa ráo nước.',
      'Chất liệu nhựa PP nguyên sinh, không BPA, an toàn thực phẩm.',
      'Hình chữ nhật tiết kiệm không gian.',
      'Lỗ thoát nước thiết kế đều, rau củ ráo nhanh.',
      'Có tay cầm chắc chắn, dễ dàng di chuyển.',
    ],
    usage: [
      'Rửa rau, trái cây, vo gạo.',
      'Ngâm rửa thực phẩm với lớp rá bên dưới.',
      'Ráo nước sau khi rửa.',
    ],
    storage: [
      'Rửa sạch sau mỗi lần sử dụng.',
      'Phơi khô hoặc lau khô trước khi cất.',
      'Tránh để gần nguồn nhiệt cao.',
    ],
    colors: [
      { name: 'Trắng', hex: '#FFFFFF' },
      { name: 'Xanh mint', hex: '#0D6E6E' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Nhựa PP' },
      { label: 'Dung tích', value: '4L' },
      { label: 'Kích thước', value: '32 x 22 x 12 cm' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Rổ lỗ thoát nước', 'Rá đựng bên dưới'],
    features: ['2 lớp tiện lợi', 'An toàn thực phẩm', 'Tiết kiệm không gian'],
  },
  6: {
    id: 6,
    name: 'Bộ giá treo khăn tắm inox 304',
    category: 'bathroom',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    ],
    rating: 5,
    reviews: 97,
    badge: '-27%',
    price: 219000,
    originalPrice: 299000,
    description: 'Bộ giá treo khăn tắm inox 304, thiết kế sang trọng, chịu lực tốt, chống gỉ sét trong môi trường ẩm ướt.',
    productInfo: 'Bộ giá treo khăn tắm được chế tạo từ inox 304 cao cấp, đảm bảo độ bền và khả năng chống gỉ vượt trội trong môi trường phòng tắm ẩm ướt. Thiết kế thanh đôi với khoảng cách hợp lý, cho phép treo 2-4 khăn tắm cùng lúc, khăn nhanh khô hơn nhờ lưu thông không khí tốt.',
    advantages: [
      'Inox 304 cao cấp, chống gỉ tuyệt đối.',
      'Thiết kế thanh đôi, treo được 2-4 khăn cùng lúc.',
      'Chịu lực lên đến 15kg.',
      'Bề mặt bóng sáng, dễ vệ sinh.',
      'Đi kèm đầy đủ phụ kiện lắp đặt.',
    ],
    usage: [
      'Lắp đặt trên tường phòng tắm bằng vít nở.',
      'Treo khăn tắm, khăn mặt, quần áo nhẹ.',
    ],
    storage: [
      'Lau khô bề mặt inox định kỳ để giữ bóng sáng.',
      'Tránh va đập mạnh.',
    ],
    colors: [
      { name: 'Bạc', hex: '#C0C0C0' },
      { name: 'Đen mờ', hex: '#2D2D2D' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Inox 304' },
      { label: 'Kích thước', value: '60 x 12 x 10 cm' },
      { label: 'Tải trọng', value: '15kg' },
      { label: 'Lắp đặt', value: 'Khoan tường' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Giá treo khăn', 'Bộ vít nở', 'Hướng dẫn lắp đặt'],
    features: ['Inox 304 chống gỉ', 'Chịu lực 15kg', 'Thanh đôi tiện lợi'],
  },
  7: {
    id: 7,
    name: 'Bộ dao nhà bếp 6 món lưỡi thép không gỉ',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1593618998160-e34014e67546?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    rating: 5,
    reviews: 156,
    badge: 'Mới',
    price: 389000,
    originalPrice: null,
    description: 'Bộ dao nhà bếp 6 món với lưỡi thép không gỉ sắc bén, tay cầm chống trượt. Gồm đầy đủ các loại dao cho mọi nhu cầu nấu nướng.',
    productInfo: 'Bộ dao nhà bếp 6 món cao cấp được rèn từ thép không gỉ X50CrMoV15, giữ độ sắc bền lâu. Tay cầm ergonomic bằng nhựa ABS chống trượt, cân bằng trọng lượng hoàn hảo. Bộ gồm: dao đầu bếp 20cm, dao thái 18cm, dao gọt 9cm, dao cắt bánh mì, kéo nhà bếp và thanh mài dao.',
    advantages: [
      'Lưỡi thép không gỉ X50CrMoV15, sắc bén lâu dài.',
      'Tay cầm ergonomic chống trượt, sử dụng an toàn.',
      'Bộ 6 món đầy đủ cho mọi nhu cầu nấu nướng.',
      'Đi kèm thanh mài dao để duy trì độ sắc.',
      'Thiết kế cân bằng trọng lượng hoàn hảo.',
    ],
    usage: [
      'Dao đầu bếp: cắt thịt, rau củ đa năng.',
      'Dao thái: thái mỏng thịt, cá.',
      'Dao gọt: gọt trái cây, tỉa rau.',
      'Rửa tay và lau khô ngay sau sử dụng.',
    ],
    storage: [
      'Không ngâm trong nước lâu.',
      'Lau khô sau khi rửa để tránh oxy hóa.',
      'Cất trong hộp đựng hoặc giá dao chuyên dụng.',
      'Mài dao định kỳ bằng thanh mài đi kèm.',
    ],
    colors: [
      { name: 'Đen', hex: '#1A1A1A' },
      { name: 'Bạc', hex: '#C0C0C0' },
    ],
    specs: [
      { label: 'Chất liệu lưỡi', value: 'Thép không gỉ X50CrMoV15' },
      { label: 'Tay cầm', value: 'Nhựa ABS chống trượt' },
      { label: 'Bộ gồm', value: '6 món' },
      { label: 'Xuất xứ', value: 'Đức' },
    ],
    inTheBox: ['Dao đầu bếp 20cm', 'Dao thái 18cm', 'Dao gọt 9cm', 'Dao cắt bánh mì', 'Kéo nhà bếp', 'Thanh mài dao'],
    features: ['Thép Đức cao cấp', '6 món đầy đủ', 'Chống trượt an toàn'],
  },
  8: {
    id: 8,
    name: 'Máy xay sinh tố đa năng 1.5L',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1570222094114-d054a817e56b?w=800&q=80',
      'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=800&q=80',
    ],
    rating: 4,
    reviews: 89,
    badge: '-15%',
    price: 549000,
    originalPrice: 649000,
    description: 'Máy xay sinh tố đa năng 1.5L công suất 600W, xay nhuyễn mịn, phù hợp làm sinh tố, nước ép, xay đá.',
    productInfo: 'Máy xay sinh tố đa năng 1.5L với động cơ 600W mạnh mẽ, lưỡi dao 6 cánh bằng thép không gỉ xay nhuyễn mọi loại trái cây, rau củ và đá trong vài giây. Cối xay bằng thủy tinh chịu nhiệt Borosilicate an toàn, không chứa BPA. Có 3 tốc độ và chế độ Pulse cho phép điều chỉnh linh hoạt.',
    advantages: [
      'Động cơ 600W mạnh mẽ, xay nhuyễn nhanh chóng.',
      'Cối thủy tinh chịu nhiệt Borosilicate an toàn.',
      'Lưỡi dao 6 cánh thép không gỉ, sắc bén.',
      '3 tốc độ + chế độ Pulse linh hoạt.',
      'Nắp đậy kín, chống tràn khi xay.',
      'Đế chống trượt, hoạt động ổn định.',
    ],
    usage: [
      'Xay sinh tố trái cây, rau xanh.',
      'Xay đá, làm đồ uống mát lạnh.',
      'Xay các loại hạt, gia vị.',
      'Không xay liên tục quá 3 phút, nghỉ 1 phút giữa các lần.',
    ],
    storage: [
      'Rửa sạch cối ngay sau khi sử dụng.',
      'Không ngâm phần thân máy trong nước.',
      'Lau khô và cất nơi khô ráo.',
    ],
    colors: [
      { name: 'Đen', hex: '#1A1A1A' },
      { name: 'Trắng', hex: '#F5F5F5' },
    ],
    specs: [
      { label: 'Công suất', value: '600W' },
      { label: 'Dung tích', value: '1.5L' },
      { label: 'Chất liệu cối', value: 'Thủy tinh Borosilicate' },
      { label: 'Tốc độ', value: '3 tốc độ + Pulse' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['Máy xay', 'Cối thủy tinh 1.5L', 'Nắp cối', 'Hướng dẫn sử dụng'],
    features: ['600W mạnh mẽ', 'Thủy tinh chịu nhiệt', '3 tốc độ'],
  },
  9: {
    id: 9,
    name: 'Gương phòng tắm có đèn LED cảm ứng',
    category: 'bathroom',
    image: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=800&q=80',
      'https://images.unsplash.com/photo-1620626011761-996317b8d101?w=800&q=80',
    ],
    rating: 5,
    reviews: 73,
    badge: null,
    price: 890000,
    originalPrice: null,
    description: 'Gương phòng tắm có đèn LED cảm ứng, chống sương mù, ánh sáng trắng tự nhiên giúp trang điểm và vệ sinh.',
    productInfo: 'Gương phòng tắm LED cao cấp tích hợp đèn LED viền sáng đều, công nghệ cảm ứng chạm bật/tắt tiện lợi. Tính năng chống sương mù (anti-fog) giúp gương luôn rõ nét ngay cả khi tắm nước nóng. Gương soi HD phản chiếu trung thực, viền bo tròn an toàn. Tiết kiệm điện với LED tiêu thụ chỉ 18W.',
    advantages: [
      'Đèn LED viền sáng đều, ánh sáng trắng tự nhiên 6000K.',
      'Cảm ứng chạm bật/tắt, điều chỉnh độ sáng.',
      'Công nghệ chống sương mù anti-fog.',
      'Gương HD phản chiếu trung thực.',
      'Tiết kiệm điện, LED chỉ 18W.',
      'Chống nước IP44, an toàn phòng tắm.',
    ],
    usage: [
      'Lắp đặt trên tường phòng tắm bằng vít nở hoặc keo dán.',
      'Chạm nhẹ vào cảm ứng để bật/tắt đèn, chạm giữ để điều chỉnh độ sáng.',
      'Bật tính năng chống sương 5 phút trước khi tắm.',
    ],
    storage: [
      'Lau gương bằng khăn mềm, tránh chất tẩy mạnh.',
      'Kiểm tra dây điện định kỳ.',
      'Không sử dụng nếu dây điện bị hở.',
    ],
    colors: [
      { name: 'Bạc', hex: '#C0C0C0' },
    ],
    specs: [
      { label: 'Kích thước', value: '60 x 80 cm' },
      { label: 'Công suất LED', value: '18W' },
      { label: 'Nhiệt độ màu', value: '6000K' },
      { label: 'Chống nước', value: 'IP44' },
      { label: 'Chống sương', value: 'Có' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['Gương LED', 'Bộ phụ kiện treo', 'Dây nguồn', 'Hướng dẫn lắp đặt'],
    features: ['LED cảm ứng', 'Chống sương mù', 'IP44 chống nước'],
  },
  10: {
    id: 10,
    name: 'Bộ ga giường cotton cao cấp 4 món',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&q=80',
    ],
    rating: 5,
    reviews: 215,
    badge: 'Mới',
    price: 599000,
    originalPrice: null,
    description: 'Bộ ga giường cotton cao cấp 4 món, mềm mại thoáng khí, phù hợp mọi mùa, nệm 1m6 và 1m8.',
    productInfo: 'Bộ ga giường cotton cao cấp 4 món được dệt từ sợi cotton 100% tự nhiên, mật độ 300TC (thread count) cho cảm giác mềm mại, mịn màng và thoáng khí. Bộ gồm 1 ga trải, 1 ga phủ và 2 vỏ gối. Chun bo quanh ga trải giúp ôm nệm chắc chắn, không bị xô lệch khi ngủ.',
    advantages: [
      'Cotton 100% tự nhiên, mềm mại thoáng khí.',
      'Mật độ 300TC, cảm giác mịn màng cao cấp.',
      'Chun bo quanh ga trải, ôm nệm chắc chắn.',
      'Nhuộm màu bền, không phai sau nhiều lần giặt.',
      'Phù hợp mọi mùa, thấm hút mồ hôi tốt.',
    ],
    usage: [
      'Phù hợp nệm kích thước 1m6 và 1m8.',
      'Giặt máy ở chế độ nhẹ, nước lạnh hoặc ấm dưới 40°C.',
      'Không sử dụng thuốc tẩy.',
    ],
    storage: [
      'Phơi trong bóng râm, tránh ánh nắng trực tiếp.',
      'Gấp gọn, cất nơi khô ráo, thoáng mát.',
      'Có thể ủi ở nhiệt độ trung bình nếu cần.',
    ],
    colors: [
      { name: 'Trắng kem', hex: '#F5F0E8' },
      { name: 'Xám nhạt', hex: '#D1D5DB' },
      { name: 'Xanh pastel', hex: '#B8D8D0' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Cotton 100%, 300TC' },
      { label: 'Bộ gồm', value: '1 ga trải, 1 ga phủ, 2 vỏ gối' },
      { label: 'Kích thước', value: '1m6 / 1m8' },
      { label: 'Giặt máy', value: 'Có, chế độ nhẹ' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['1 ga trải giường', '1 ga phủ', '2 vỏ gối', 'Túi đựng'],
    features: ['Cotton 100%', 'Chun bo ôm nệm', 'Thoáng khí 4 mùa'],
  },
  11: {
    id: 11,
    name: 'Đèn bàn LED chống cận thị',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1507473885765-e6ed057ab6fe?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    ],
    rating: 4,
    reviews: 67,
    badge: null,
    price: 329000,
    originalPrice: null,
    description: 'Đèn bàn LED chống cận thị với 3 chế độ ánh sáng, điều chỉnh độ sáng, bảo vệ mắt khi học tập và làm việc.',
    productInfo: 'Đèn bàn LED chống cận thị sử dụng công nghệ LED không nhấp nháy (flicker-free) và chống chói (anti-glare), bảo vệ mắt hiệu quả khi học tập và làm việc lâu dài. Với 3 chế độ ánh sáng (trắng, vàng, trung tính) và 5 mức độ sáng điều chỉnh, phù hợp mọi nhu cầu sử dụng.',
    advantages: [
      'Công nghệ LED không nhấp nháy, chống cận thị.',
      'Chống chói anti-glare, bảo vệ mắt.',
      '3 chế độ ánh sáng + 5 mức độ sáng.',
      'Cổ đèn linh hoạt, xoay 180°.',
      'Hẹn giờ tắt tự động 30/60 phút.',
      'Tiết kiệm điện, chỉ 8W.',
    ],
    usage: [
      'Đặt trên bàn học, bàn làm việc.',
      'Chọn chế độ ánh sáng phù hợp: trắng cho học tập, vàng cho thư giãn.',
      'Sử dụng hẹn giờ để tiết kiệm điện.',
    ],
    storage: [
      'Tránh đặt ở nơi ẩm ướt.',
      'Lau bụi thường xuyên bằng khăn mềm.',
      'Không che đèn khi đang hoạt động.',
    ],
    colors: [
      { name: 'Trắng', hex: '#FFFFFF' },
      { name: 'Đen', hex: '#1A1A1A' },
    ],
    specs: [
      { label: 'Công suất', value: '8W' },
      { label: 'Chế độ ánh sáng', value: '3 chế độ' },
      { label: 'Mức độ sáng', value: '5 mức' },
      { label: 'Hẹn giờ', value: '30/60 phút' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['Đèn bàn LED', 'Adapter nguồn', 'Hướng dẫn sử dụng'],
    features: ['Chống cận thị', '3 chế độ sáng', 'Hẹn giờ tắt'],
  },
  12: {
    id: 12,
    name: 'Nồi áp suất điện đa năng 6L',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1585664811087-47f65abbad64?w=800&q=80',
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80',
    ],
    rating: 5,
    reviews: 312,
    badge: '-20%',
    price: 1190000,
    originalPrice: 1490000,
    description: 'Nồi áp suất điện đa năng 6L với 12 chương trình nấu tự động, nấu cơm, hầm xương, nấu cháo, hấp.',
    productInfo: 'Nồi áp suất điện đa năng 6L tích hợp 12 chương trình nấu tự động: nấu cơm, hầm, ninh, nấu cháo, hấp, làm bánh, nấu soup, slow cook... Lòng nồi phủ chống dính ceramic 5 lớp an toàn sức khỏe. Hệ thống 7 cơ chế an toàn bảo vệ chống quá áp, quá nhiệt. Bảng điều khiển LED dễ sử dụng, hẹn giờ lên đến 24h.',
    advantages: [
      '12 chương trình nấu tự động đa năng.',
      'Lòng nồi ceramic 5 lớp chống dính, an toàn.',
      '7 cơ chế an toàn bảo vệ toàn diện.',
      'Hẹn giờ lên đến 24 giờ.',
      'Giữ ấm tự động sau khi nấu.',
      'Tiết kiệm 70% thời gian nấu so với nồi thường.',
    ],
    usage: [
      'Chọn chương trình nấu phù hợp trên bảng điều khiển.',
      'Không đổ nguyên liệu quá 2/3 dung tích nồi.',
      'Đợi áp suất xả hết trước khi mở nắp.',
    ],
    storage: [
      'Rửa lòng nồi bằng nước ấm, không dùng miếng cọ cứng.',
      'Lau khô thân nồi, không ngâm nước.',
      'Kiểm tra gioăng cao su định kỳ.',
    ],
    colors: [
      { name: 'Bạc', hex: '#C0C0C0' },
      { name: 'Đen', hex: '#1A1A1A' },
    ],
    specs: [
      { label: 'Dung tích', value: '6L' },
      { label: 'Công suất', value: '1000W' },
      { label: 'Chương trình', value: '12 chương trình' },
      { label: 'Lòng nồi', value: 'Ceramic 5 lớp' },
      { label: 'Hẹn giờ', value: '24 giờ' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Nồi áp suất', 'Xửng hấp', 'Muỗng múc', 'Cốc đong', 'Hướng dẫn sử dụng'],
    features: ['12 chương trình', '7 cơ chế an toàn', 'Hẹn giờ 24h'],
  },
  13: {
    id: 13,
    name: 'Bộ ly thuỷ tinh chịu nhiệt 6 cái',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed514?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1513558161293-cdaf765ed514?w=800&q=80',
      'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=800&q=80',
    ],
    rating: 4,
    reviews: 54,
    badge: null,
    price: 189000,
    originalPrice: null,
    description: 'Bộ ly thuỷ tinh chịu nhiệt 6 cái, dùng được cho đồ uống nóng và lạnh, thiết kế hiện đại.',
    productInfo: 'Bộ ly thuỷ tinh chịu nhiệt 6 cái được làm từ thuỷ tinh Borosilicate chịu nhiệt từ -20°C đến 150°C, có thể rót nước sôi trực tiếp mà không bị nứt vỡ. Thiết kế thành mỏng nhẹ nhưng cực kỳ bền, dung tích 350ml mỗi ly phù hợp cho trà, cà phê, nước trái cây.',
    advantages: [
      'Thuỷ tinh Borosilicate chịu nhiệt -20°C đến 150°C.',
      'Thành mỏng nhẹ, trong suốt, sang trọng.',
      'Không chứa chì, an toàn sức khỏe.',
      'Không giữ mùi, không đổi màu.',
      'Rửa được bằng máy rửa chén.',
    ],
    usage: [
      'Dùng cho đồ uống nóng và lạnh.',
      'Có thể dùng trong lò vi sóng.',
      'Không dùng trong lò nướng.',
    ],
    storage: [
      'Tránh va đập mạnh.',
      'Rửa nhẹ nhàng, tránh cọ xát bằng vật cứng.',
      'Xếp chồng cẩn thận khi cất.',
    ],
    colors: [
      { name: 'Trong suốt', hex: '#E8E8E8' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Thuỷ tinh Borosilicate' },
      { label: 'Dung tích', value: '350ml/ly' },
      { label: 'Số lượng', value: '6 cái' },
      { label: 'Chịu nhiệt', value: '-20°C đến 150°C' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['6 ly thuỷ tinh', 'Hộp đựng bảo quản'],
    features: ['Chịu nhiệt cao', 'Không chì', 'Dùng cho lò vi sóng'],
  },
  14: {
    id: 14,
    name: 'Máy hút bụi cầm tay không dây',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558317374-067fb5f30001?w=800&q=80',
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
    ],
    rating: 5,
    reviews: 178,
    badge: 'Mới',
    price: 1890000,
    originalPrice: null,
    description: 'Máy hút bụi cầm tay không dây, lực hút 25000Pa, pin lithium 45 phút, phù hợp sàn nhà và sofa.',
    productInfo: 'Máy hút bụi cầm tay không dây thế hệ mới với motor không chổi than công suất 350W, lực hút lên đến 25,000Pa. Pin lithium 2500mAh cho thời gian hoạt động lên đến 45 phút ở chế độ thường. Thiết kế 2-trong-1 dễ dàng chuyển đổi giữa mode đứng và mode cầm tay, kèm 4 đầu hút chuyên dụng.',
    advantages: [
      'Lực hút 25,000Pa mạnh mẽ, hút sạch bụi mịn.',
      'Pin lithium 2500mAh, sử dụng 45 phút liên tục.',
      'Motor không chổi than bền bỉ, ít tiếng ồn.',
      'Thiết kế 2-trong-1 linh hoạt.',
      '4 đầu hút chuyên dụng cho mọi bề mặt.',
      'Bộ lọc HEPA lọc bụi mịn 0.3μm.',
    ],
    usage: [
      'Sạc đầy pin trước khi sử dụng lần đầu (4-5 giờ).',
      'Chọn đầu hút phù hợp cho từng bề mặt.',
      'Vệ sinh bộ lọc HEPA sau mỗi 2-3 lần sử dụng.',
    ],
    storage: [
      'Sạc đầy pin nếu không sử dụng trong thời gian dài.',
      'Vệ sinh thùng chứa bụi sau mỗi lần sử dụng.',
      'Treo gọn bằng giá treo tường đi kèm.',
    ],
    colors: [
      { name: 'Trắng', hex: '#F5F5F5' },
      { name: 'Xám', hex: '#6B7280' },
    ],
    specs: [
      { label: 'Công suất', value: '350W' },
      { label: 'Lực hút', value: '25,000Pa' },
      { label: 'Pin', value: 'Lithium 2500mAh' },
      { label: 'Thời gian sạc', value: '4-5 giờ' },
      { label: 'Thời gian dùng', value: '45 phút' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['Máy hút bụi', '4 đầu hút', 'Bộ sạc', 'Giá treo tường', 'Hướng dẫn sử dụng'],
    features: ['25,000Pa lực hút', 'Pin 45 phút', 'HEPA lọc bụi mịn'],
  },
  15: {
    id: 15,
    name: 'Hộp đựng giày trong suốt xếp chồng',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1491553895911-0055eca6402d?w=800&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    ],
    rating: 4,
    reviews: 92,
    badge: '-25%',
    price: 149000,
    originalPrice: 199000,
    description: 'Hộp đựng giày trong suốt xếp chồng, bộ 6 hộp, nắp mở từ tính, bảo quản giày gọn gàng.',
    productInfo: 'Hộp đựng giày trong suốt xếp chồng bộ 6 hộp, thiết kế nắp mở bằng nam châm tiện lợi, nhìn thấy giày bên trong không cần mở nắp. Chất liệu nhựa PP dày dặn, chịu lực tốt, có thể xếp chồng 6-8 tầng. Lỗ thông hơi ở thành hộp giúp giày luôn khô ráo, không bị ẩm mốc.',
    advantages: [
      'Trong suốt, dễ nhìn thấy giày bên trong.',
      'Nắp mở từ tính, đóng mở tiện lợi.',
      'Xếp chồng được 6-8 tầng, tiết kiệm không gian.',
      'Lỗ thông hơi chống ẩm mốc.',
      'Chất liệu PP dày dặn, chịu lực tốt.',
    ],
    usage: [
      'Xếp giày vào hộp, đóng nắp từ tính.',
      'Có thể xếp chồng nhiều tầng.',
      'Phù hợp giày nam size đến 44, giày nữ mọi size.',
    ],
    storage: [
      'Lau sạch hộp bằng khăn ẩm.',
      'Để giày khô trước khi cho vào hộp.',
      'Đặt nơi khô ráo, thoáng mát.',
    ],
    colors: [
      { name: 'Trong suốt', hex: '#E8E8E8' },
      { name: 'Trắng đục', hex: '#F0F0F0' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'Nhựa PP' },
      { label: 'Kích thước/hộp', value: '33 x 23 x 14 cm' },
      { label: 'Số lượng', value: '6 hộp/bộ' },
      { label: 'Chịu lực', value: 'Xếp 6-8 tầng' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['6 hộp đựng giày', '6 nắp từ tính'],
    features: ['Nắp từ tính', 'Xếp chồng gọn', 'Thông hơi chống ẩm'],
  },
  16: {
    id: 16,
    name: 'Vòi sen tăng áp tiết kiệm nước',
    category: 'bathroom',
    image: 'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1585412727339-54e4bae3bbf9?w=800&q=80',
      'https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=800&q=80',
    ],
    rating: 5,
    reviews: 141,
    badge: null,
    price: 159000,
    originalPrice: null,
    description: 'Vòi sen tăng áp tiết kiệm nước lên đến 40%, 3 chế độ phun, lắp đặt dễ dàng.',
    productInfo: 'Vòi sen tăng áp sử dụng công nghệ Turbo tạo áp lực nước mạnh gấp 3 lần so với vòi sen thường, đồng thời tiết kiệm đến 40% lượng nước sử dụng. Với 3 chế độ phun (mưa, massage, tia tập trung), vòi sen mang đến trải nghiệm tắm thư giãn tuyệt vời. Bộ lọc nano kháng khuẩn tích hợp giúp lọc tạp chất, bảo vệ da.',
    advantages: [
      'Tăng áp gấp 3 lần, mạnh mẽ ngay cả áp nước yếu.',
      'Tiết kiệm 40% lượng nước sử dụng.',
      '3 chế độ phun linh hoạt.',
      'Bộ lọc nano kháng khuẩn bảo vệ da.',
      'Lắp đặt dễ dàng, tương thích mọi loại ống nước tiêu chuẩn.',
    ],
    usage: [
      'Tháo vòi sen cũ, lắp vòi sen mới bằng tay (không cần dụng cụ).',
      'Xoay nút trên đầu vòi để chuyển chế độ phun.',
      'Thay bộ lọc nano mỗi 3-6 tháng.',
    ],
    storage: [
      'Vệ sinh đầu phun định kỳ để tránh tắc cặn.',
      'Ngâm trong giấm pha loãng 30 phút nếu bị cặn.',
    ],
    colors: [
      { name: 'Bạc', hex: '#C0C0C0' },
      { name: 'Trắng', hex: '#FFFFFF' },
    ],
    specs: [
      { label: 'Chất liệu', value: 'ABS + Inox' },
      { label: 'Chế độ phun', value: '3 chế độ' },
      { label: 'Tiết kiệm nước', value: '40%' },
      { label: 'Đường kính kết nối', value: 'Tiêu chuẩn G1/2' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Vòi sen tăng áp', 'Dây sen 1.5m', 'Bộ lọc nano', 'Giá đỡ tường', 'Hướng dẫn lắp đặt'],
    features: ['Tăng áp 3 lần', 'Tiết kiệm 40% nước', 'Bộ lọc nano'],
  },
  17: {
    id: 17,
    name: 'Bàn ủi hơi nước đứng 1800W',
    category: 'living',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800&q=80',
      'https://images.unsplash.com/photo-1616486338812-3dadae4b4ace?w=800&q=80',
    ],
    rating: 4,
    reviews: 63,
    badge: '-18%',
    price: 890000,
    originalPrice: 1090000,
    description: 'Bàn ủi hơi nước đứng 1800W, làm phẳng nhanh mọi loại vải, bình chứa nước 1.8L.',
    productInfo: 'Bàn ủi hơi nước đứng công suất 1800W cho lượng hơi nước lớn và liên tục, làm phẳng nếp nhăn nhanh chóng trên mọi loại vải từ cotton, lụa đến len. Bình chứa nước 1.8L cho thời gian ủi liên tục 45 phút. Đầu phun hơi bằng thép không gỉ, thanh treo quần áo đi kèm tiện lợi.',
    advantages: [
      'Công suất 1800W, hơi nước mạnh liên tục.',
      'Bình nước 1.8L, ủi liên tục 45 phút.',
      'Phù hợp mọi loại vải: cotton, lụa, len, polyester.',
      'Đầu phun inox, nóng nhanh trong 45 giây.',
      'Thanh treo quần áo đi kèm.',
      'Tự tắt an toàn khi hết nước.',
    ],
    usage: [
      'Đổ nước vào bình, bật máy và đợi 45 giây.',
      'Treo quần áo lên thanh treo, ủi từ trên xuống.',
      'Giữ đầu phun cách vải 2-3cm để tránh ướt vải.',
    ],
    storage: [
      'Xả hết nước sau mỗi lần sử dụng.',
      'Để nguội trước khi cất.',
      'Quấn dây điện gọn gàng.',
    ],
    colors: [
      { name: 'Xanh đậm', hex: '#1E3A5F' },
      { name: 'Trắng', hex: '#F5F5F5' },
    ],
    specs: [
      { label: 'Công suất', value: '1800W' },
      { label: 'Bình nước', value: '1.8L' },
      { label: 'Thời gian nóng', value: '45 giây' },
      { label: 'Thời gian ủi', value: '45 phút liên tục' },
      { label: 'Xuất xứ', value: 'Trung Quốc' },
    ],
    inTheBox: ['Bàn ủi hơi nước đứng', 'Thanh treo quần áo', 'Găng tay chống nóng', 'Hướng dẫn sử dụng'],
    features: ['1800W mạnh mẽ', 'Nóng trong 45 giây', '45 phút liên tục'],
  },
  18: {
    id: 18,
    name: 'Máy lọc nước RO 10 lõi',
    category: 'kitchen',
    image: 'https://images.unsplash.com/photo-1564419320461-6870880221ad?w=600&q=80',
    images: [
      'https://images.unsplash.com/photo-1564419320461-6870880221ad?w=800&q=80',
      'https://images.unsplash.com/photo-1556909172-54557c7e4fb7?w=800&q=80',
    ],
    rating: 5,
    reviews: 287,
    badge: 'Mới',
    price: 4990000,
    originalPrice: null,
    description: 'Máy lọc nước RO 10 lõi, lọc sạch 99.9% vi khuẩn, bổ sung khoáng chất, không cần cắm điện.',
    productInfo: 'Máy lọc nước RO 10 lõi lọc sử dụng công nghệ thẩm thấu ngược (Reverse Osmosis) với màng lọc RO 0.0001μm loại bỏ 99.9% vi khuẩn, virus, kim loại nặng và tạp chất. Hệ thống 10 lõi lọc đa tầng kết hợp bổ sung khoáng chất tự nhiên (Ca, Mg, K) cho nước uống trực tiếp. Thiết kế gầm tủ bếp gọn gàng, vòi inox 304 cao cấp.',
    advantages: [
      'Công nghệ RO loại bỏ 99.9% vi khuẩn, kim loại nặng.',
      'Hệ thống 10 lõi lọc đa tầng.',
      'Bổ sung khoáng chất tự nhiên Ca, Mg, K.',
      'Nước uống trực tiếp tại vòi.',
      'Thiết kế gầm tủ gọn gàng.',
      'Vòi inox 304 cao cấp, bền bỉ.',
    ],
    usage: [
      'Lắp đặt bởi kỹ thuật viên chuyên nghiệp.',
      'Mở vòi lấy nước uống trực tiếp.',
      'Xả nước 3-5 phút khi sử dụng lần đầu.',
    ],
    storage: [
      'Thay lõi lọc theo lịch: lõi 1-3 mỗi 6 tháng, lõi RO mỗi 24 tháng.',
      'Không để máy ngưng hoạt động quá 7 ngày.',
      'Vệ sinh vòi nước định kỳ.',
    ],
    colors: [
      { name: 'Trắng', hex: '#FFFFFF' },
    ],
    specs: [
      { label: 'Công nghệ', value: 'RO (Reverse Osmosis)' },
      { label: 'Số lõi lọc', value: '10 lõi' },
      { label: 'Tốc độ lọc', value: '10L/giờ' },
      { label: 'Màng lọc RO', value: '0.0001μm' },
      { label: 'Vòi nước', value: 'Inox 304' },
      { label: 'Xuất xứ', value: 'Việt Nam' },
    ],
    inTheBox: ['Máy lọc nước', 'Vòi inox 304', 'Bộ dây nối', 'Hướng dẫn lắp đặt', 'Phiếu bảo hành 5 năm'],
    features: ['RO 10 lõi lọc', 'Loại bỏ 99.9% vi khuẩn', 'Bổ sung khoáng chất'],
  },
}

export default defineEventHandler(async (event) => {
  // Cache response
  setResponseHeaders(event, {
    'Cache-Control': 'public, s-maxage=60, stale-while-revalidate=300',
    'Content-Type': 'application/json',
  })

  const id = Number(getRouterParam(event, 'id'))

  if (!id || isNaN(id) || id < 1 || id > 18) {
    throw createError({
      statusCode: 404,
      statusMessage: 'Product not found',
    })
  }

  const product = productDetails[id]
  if (!product) {
    throw createError({
      statusCode: 404,
      statusMessage: 'Product not found',
    })
  }

  return product
})

